language: cpp

before_install:
  - wget https://github.com/google/googletest/archive/master.zip
  - unzip master.zip 
  - cd googletest-master/googletest/
  - ls . -a
  # ./configure --prefix=$TRAVIS_BUILD_DIR --with-pthreads=no
  - cmake .
  - make clean
  - make all
  - ls . -a
  - ls ./include/ -a
  - pwd
  - ls ../
  - ls ../../
  - ls ../../../
  
script:
  - make googletest
