# CS 3505, A4 - Testing and Travis
# Snehashish Mishra and Nick Porter

language: cpp
install: true
compiler: gcc

addons:
  apt:
    packages:
    - g++-4.8
    - gcc-4.8
    sources:
    - ubuntu-toolchain-r-test
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y g++-4.8; export CXX="g++-4.8";
  - wget https://github.com/google/googletest/archive/master.zip
  - unzip master.zip 
  - cd googletest-master/googletest/
  - cmake .
  - make clean
  - make all
  - mv /home/travis/build/University-of-Utah-CS3505/cs3505-a4-googletest-nick-ash/googletest-master /home/travis/build/
  - cd /home/travis/build/University-of-Utah-CS3505/cs3505-a4-googletest-nick-ash/
  
script:
  - make test GOOGLETEST=../../googletest-master/googletest/
