language: cpp
compiler: g++
sudo: false

addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - g++-4.8

before_script:
    - uname -a
    - printenv
    - g++ --version 2>&1 | grep g++
    
install: 
 # Install gtest without sudo 
    - mkdir ~/gtest && cd ~/gtest
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - cd -
    
script:
    - make CXX=g++-4.8 GOOGLETESTS=gtest/googletests/
    - ./StudentTests
