language: cpp

addons:
  apt:
    packages:
    - g++-4.8
    - gcc-4.8
    sources:
    - ubuntu-toolchain-r-test

before_install:
  - wget https://github.com/google/googletest/archive/master.zip
  - unzip master.zip 
  - cd googletest-master/googletest/
  - ls . -a
  # ./configure --prefix=$TRAVIS_BUILD_DIR --with-pthreads=no
  - cmake .
  - make clean
  - make all
  - mv /home/travis/build/University-of-Utah-CS3505/cs3505-a4-googletest-nick-ash/googletest-master /home/travis/build/
  - ls . -a
  - ls ./include/ -a
  - pwd
  - ls ../
  - ls ../../
  - ls ../../googletest-master/googletest/ -a
  - cd /home/travis/build/University-of-Utah-CS3505/cs3505-a4-googletest-nick-ash/
  - pwd
  - ls -a
  
script:
  - make CC=gcc-4.8 CXX=g++-4.8 && make install
  - make test GOOGLETEST=../../googletest-master/googletest/
