language: cpp

before_install:
  - wget https://github.com/google/googletest/archive/googletest-master.zip
  - unzip googletest-master.zip 
  - cd googletest-master/googletest/
  - ./configure --prefix=$TRAVIS_BUILD_DIR --with-pthreads=no
  - make
  - mkdir $TRAVIS_BUILD_DIR/include/
  - cp -r include/gtest $TRAVIS_BUILD_DIR/include
  - mkdir $TRAVIS_BUILD_DIR/lib/
  - cp lib/.libs/* $TRAVIS_BUILD_DIR/lib/
  - cd ..
  - export CPLUS_INCLUDE_PATH=$TRAVIS_BUILD_DIR/include:$CPLUS_INCLUDE_PATH
  - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib:$LD_LIBRARY_PATH
  - ls .
  - ls ../
  - ls ../../
  - ls ../../../
  - cd cpp

script:
  - make googletest
