language: cpp
compiler: gcc
sudo: false

addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - gcc-4.8 
      - g++-4.8

before_script:
    - uname -a
    - printenv
    - g++ --version 2>&1 | grep g++
    
install: 
    # Install gtest without sudo 
    - mkdir ~/gtest && cd ~/gtest
    - export LIBRARY_PATH=$(pwd)
    - ls
    - pwd
    - cp -r /home/travis/gtest/* ./
    - ls
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - ls
    - make
    - cd -
    - ls
    
script:
    - make CXX=g++-4.8 GOOGLETESTS=gtest/googletests/
    - ./StudentTests
