language: cpp
compiler: gcc
sudo: false

addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - gcc-4.8 
      - g++-4.8
      - gcov-4.6
      - clang
      - doxygen
      - valgrind
      - libgtest-dev
      - libboost-dev

before_script:
    - uname -a
    - printenv
    - clang++ --version 2>&1 | grep clang
    - g++ --version 2>&1 | grep g++
    - gcov --version | grep gcov
    - valgrind --version
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
    - doxygen --version

install: 
    # Install gtest without sudo 
    - mkdir ~/gtest && mkdir ~/gtest/include && cd ~/gtest
    - export CPLUS_INCLUDE_PATH=$(pwd)/include
    - export LIBRARY_PATH=$(pwd)
    - ls .
    - cp -r /usr/src/gtest/* ./
    - cp -r /usr/src/gtest/include/* ./include/
    # cp -r /usr/src/gtest/* ./
    - pwd
    - ls .
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./ CMakeLists.txt
    - make
    - cd -
    - pwd
    - ls .
    - ls ../
    - ls ../../
    - ls ../../../
    - ls ../../../gtest/
    - ls ../../../gtest/include/
    - ls ../../../build/
    - ls ../../../builds/
    - ls ../../../gtest/src/
    - ls ../../../../
    - ls ../../../../vagrant/
    - ls ../../../../travis/
    - ls -R / | awk '/:$/&&f{s=$0;f=0} /:$/&&!f{sub(/:$/,"");s=$0;f=1;next} NF&&f{ print s"/"$0 }'
    
    
script:
    - make GOOGLETEST=../../../gtest
    - ./StudentsTests
